name: Build Direct APK

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

# 🔴 Yeh permission zaroori hai taaki GitHub direct file upload kar sake
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Set up Java (JDK 17)
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Give Permission to Gradle
      run: chmod +x gradlew

    - name: Build Debug APK 🚀
      run: ./gradlew assembleDebug

    - name: Rename APK File (Saaf naam ke liye)
      run: mv app/build/outputs/apk/debug/app-debug.apk StreamVision-App.apk

    - name: Upload Direct APK 🎁
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "Auto-Build-${{ github.run_number }}"
        name: "Latest StreamVision Build"
        files: StreamVision-App.apk
